Integrate Devin's buildpack with this one.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,30 +1,33 @@
 #!/bin/sh
 
 BUILD_DIR=$1
+ENV_DIR=$3
 
 STAGE="$(mktemp -d)"
 
-# rm -rf "${BUILD_DIR}"/node_modules/electron/
-# rm -rf "${BUILD_DIR}"/node_modules/@storybook/
-# rm -rf "${BUILD_DIR}"/node_modules/canvas/
-# rm -rf "${BUILD_DIR}"/node_modules/aws-sdk/
-# rm -rf "${BUILD_DIR}"/node_modules/prettier/
-# rm -rf "${BUILD_DIR}"/node_modules/@jest*
-# rm -rf "${BUILD_DIR}"/node_modules/jest-jasmine2/
-# rm -rf "${BUILD_DIR}"/node_modules/@testing-library/
-# rm -rf "${BUILD_DIR}"/node_modules/@typescript-eslint/
-# rm -rf "${BUILD_DIR}"/node_modules/eslint*
-# rm -rf "${BUILD_DIR}"/node_modules/react-syntax-highlighter/
-# rm -rf "${BUILD_DIR}"/node_modules/cypress/
-# rm -rf "${BUILD_DIR}"/node_modules/@okta/
-# rm -rf "${BUILD_DIR}"/node_modules/mocha/
-
+# Set up folder structure to account for expected location of js-packages
 mv "${BUILD_DIR}"/* "${STAGE}"
 rm -rf "${BUILD_DIR}"/*
 mkdir "$BUILD_DIR/web/"
 mv "${STAGE}"/* "${BUILD_DIR}/web/"
 mv "/tmp/js-packages" "${BUILD_DIR}/js-packages/"
 
+# Copy the Procfile to BUILD_DIR where Heroku expects it to be
+if [ ! -f "$ENV_DIR/APP_ROOT" ]; then
+  echo "APP_ROOT not set. Aborting."
+  exit 1
+fi
+
+APP_ROOT="$(cat "$ENV_DIR/APP_ROOT")"
+
+if [ ! -d "$BUILD_DIR/$APP_ROOT" ]; then
+  echo "No project found at $APP_ROOT. Aborting."
+  exit 1
+fi
+
+cp "$BUILD_DIR/$APP_ROOT/Procfile" $BUILD_DIR/
+
+# Remove unneeded files to cut down on Heroku slug size
 rm -rf "${BUILD_DIR}"/js-packages/integration*
 rm -rf "${BUILD_DIR}"/js-packages/test-utilities/
 rm -rf "${BUILD_DIR}"/js-packages/quoting-rules/
